import "./globals.css";
import { Albert_Sans as Font } from "next/font/google";

const font = Font({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="max-w-3xl mx-auto p-8">{children}</div>
      </body>
    </html>
  );
}
